let _ = "Mint DAU token 1000000";
let account1 = principal "u4f2v-igzyj-kgr2d-ipjf5-dnkz6-sl6mm-gxues-usbeb-2bthn-pfjdq-kae";
let account2 = principal "g27n3-ynszd-oh3rr-p3xnx-vuhl4-nufyt-xlbbw-x4fsg-5pbiv-jwbkk-7qe";
let account3 = principal "psgm7-igfya-7g2cx-t5jgr-uxozt-fm7n6-xhepm-tvmw7-y4hpe-iq5o4-7qe";
let assetCanister = principal "yofga-2qaaa-aaaaa-aabsq-cai";
let assetSc = record { canister_id = principal "yofga-2qaaa-aaaaa-aabsq-cai" };
let assetStore = record { canister_id = principal "yhgn4-myaaa-aaaaa-aabta-cai" };
let assetStoreCanister = principal "yhgn4-myaaa-aaaaa-aabta-cai";
let dip20 = record { canister_id = principal "y3cxn-3yaaa-aaaaa-aabra-cai" };
let dip20Canister = principal "y3cxn-3yaaa-aaaaa-aabra-cai";
let dip721Canister = principal "y4drz-waaaa-aaaaa-aabrq-cai";
let ic = principal "aaaaa-aa";
let marketplace = record { canister_id = principal "yahli-baaaa-aaaaa-aabtq-cai" };
let marketplaceCanister = principal "yahli-baaaa-aaaaa-aabtq-cai";
let nftSc = record { canister_id = principal "y4drz-waaaa-aaaaa-aabrq-cai" };
let resp = variant { Ok = 5 : nat };
let stakingCanister = principal "yjeau-xiaaa-aaaaa-aabsa-cai";
let stakingSc = record { canister_id = principal "yjeau-xiaaa-aaaaa-aabsa-cai" };
