let _ = "Mint DAU token 1000000";
let account1 = principal "u4f2v-igzyj-kgr2d-ipjf5-dnkz6-sl6mm-gxues-usbeb-2bthn-pfjdq-kae";
let account2 = principal "g27n3-ynszd-oh3rr-p3xnx-vuhl4-nufyt-xlbbw-x4fsg-5pbiv-jwbkk-7qe";
let account3 = principal "psgm7-igfya-7g2cx-t5jgr-uxozt-fm7n6-xhepm-tvmw7-y4hpe-iq5o4-7qe";
let assetCanister = principal "xub3y-eqaaa-aaaaa-aaawq-cai";
let assetSc = record { canister_id = principal "xub3y-eqaaa-aaaaa-aaawq-cai" };
let assetStore = record { canister_id = principal "x5cqe-syaaa-aaaaa-aaaxa-cai" };
let assetStoreCanister = principal "x5cqe-syaaa-aaaaa-aaaxa-cai";
let dip20 = record { canister_id = principal "xbgkv-fyaaa-aaaaa-aaava-cai" };
let dip20Canister = principal "xbgkv-fyaaa-aaaaa-aaava-cai";
let dip721Canister = principal "xghmb-iaaaa-aaaaa-aaavq-cai";
let ic = principal "aaaaa-aa";
let marketplace = record { canister_id = principal "x2dwq-7aaaa-aaaaa-aaaxq-cai" };
let marketplaceCanister = principal "x2dwq-7aaaa-aaaaa-aaaxq-cai";
let nftSc = record { canister_id = principal "xghmb-iaaaa-aaaaa-aaavq-cai" };
let resp = variant { Ok = 5 : nat };
let stakingCanister = principal "xta5m-jiaaa-aaaaa-aaawa-cai";
let stakingSc = record { canister_id = principal "xta5m-jiaaa-aaaaa-aaawa-cai" };
